# Build the web app
FROM node:8-alpine

WORKDIR /app
COPY . .

# This will be replaced by the build script
# COPY-WHEEL-PARTS

RUN npm i npm@latest -g && \
    npm i && \
    npm run build -- loaders metadata

EXPOSE 8080
CMD [ "npm", "start" ]